
image: docker:20.10.16

pipelines:
  branches:
    main:
      - step:
          name: Build and Push to Docker Hub
          services:
            - docker
          caches:
            - docker
          script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker build -t $IMAGE_NAME:latest .
            - docker push $IMAGE_NAME:latest