
image: docker:20.10.16

pipelines:
  branches:
    main:
      - step:
          name: Build and Push to Docker Hub
          services:
            - docker
          caches:
            - docker
          script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker build -f backend/Dockerfile -t $DOCKER_USERNAME/$IMAGE_NAME:latest backend

            - docker push $DOCKER_USERNAME/$IMAGE_NAME:latest